# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "xjs.xjtu"



author:
  name:             xjs.xjtu
  #facebook:         your-id
  #twitter:          your-id
  github:           xjsXjtu
  #linkedin:         your-id
  #medium:           your-id
  #tumblr:           your-id
  email:            xjs.xjtu@gmail.com

# Google-analytics
google-analytics:
 id:               "xjs.xjtu"

# Disqus
# disqus:
#  id:               "your-id"

# URL
url:                "https://xjsXjtu.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog

# xiongjs: avoid collision
port: 4567

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Shanghai
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:

  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "About"
    url:            "/about"
  #- name:           "Github"
  #  url:            "https://github.com/AWEEKJ/Kiko-plus"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
